sudo: required
dist: trusty
language: generic
env:
    global:
        - "BUILD_NUMBER=$TRAVIS_BUILD_NUMBER"
        - "BUILD_DIR=$TRAVIS_BUILD_DIR"
before_install:
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    - sudo apt-get update -qq
    - sudo apt-get install -y libicu52 libunwind8 git-lfs=1.1.0 build-essential
    - git lfs install
    - git lfs pull
script:
    - chmod +x ./replace-version.sh
    - chmod +x ./build-msbuild.sh
    - chmod +x ./github-release.sh
    - ./replace-version.sh
    - ./build-msbuild.sh
after_success: ./github-release.sh "$TRAVIS_REPO_SLUG" "$TRAVIS_TAG" bin/Release/ETGMod.Installer.exe
