sudo: false
language: csharp
env:
    global:
        - "BUILD_NUMBER=$TRAVIS_BUILD_NUMBER"
        - "BUILD_DIR=$TRAVIS_BUILD_DIR"
script:
    - chmod +x ./replace-version.sh
    - chmod +x ./build.sh
    - chmod +x ./github-release.sh
    - ./replace-version.sh
    - ./build.sh
after_success: ./github-release.sh "$TRAVIS_REPO_SLUG" "$TRAVIS_TAG" bin/Release/ETGMod.Installer.exe
